services:
  - type: web
    name: smart-bmi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main1:app --host 0.0.0.0 --port 10000
    plan: free
    branch: main
    runtime: python
    region: oregon
    autoDeploy: true
